# Generated by Django 4.1.3 on 2022-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_comment_comfort_alter_comment_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='clean',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
