# Generated by Django 4.1.3 on 2022-12-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentImage',
        ),
    ]
