# Generated by Django 4.1.3 on 2022-11-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='clean',
            new_name='purity',
        ),
    ]
