# Generated by Django 4.1.3 on 2022-11-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_comment_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bag_review',
            new_name='bad_review',
        ),
    ]
