# Generated by Django 4.1.3 on 2022-11-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_title', models.CharField(max_length=300)),
                ('room_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('standart', 'Standart'), ('lux', 'Lux'), ('vip', 'VIP')], max_length=50)),
                ('room_capacity', models.CharField(choices=[('standart', 'Standart'), ('lux', 'Lux'), ('vip', 'VIP')], max_length=50)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_image', models.ImageField(upload_to='media')),
                ('room_area', models.PositiveIntegerField()),
                ('balcony', models.BooleanField(default=False)),
                ('garden_view', models.BooleanField(default=False)),
                ('mountain_view', models.BooleanField(default=False)),
                ('landmark_view', models.BooleanField(default=False)),
                ('city_view', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('private_bathroom', models.BooleanField(default=False)),
                ('flat_screen_TV', models.BooleanField(default=False)),
                ('soundproofing', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('mini_bar', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('coffee_machine', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room')),
            ],
        ),
    ]
