# Generated by Django 4.1.3 on 2022-12-01 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('standart', 'Standart'), ('lux', 'Lux'), ('vip', 'VIP')], max_length=50)),
                ('room_capacity', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('flat_screen_TV', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_manager', to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_num', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='room.room')),
            ],
        ),
    ]
