# Generated by Django 4.1.3 on 2022-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomnum',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
