# Generated by Django 4.1.3 on 2022-11-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('slug', models.SlugField(blank=True, max_length=400, primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('desc_list', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='hotel_images')),
                ('food', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(choices=[('chuy', 'Чуй'), ('osh', 'Ош'), ('issyk-Kul', 'Иссык-Куль'), ('talas', 'Талас'), ('naryn', 'Нарын'), ('batken', 'Баткен'), ('jalal-Abad', 'Джалал-Абад')], max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/carousel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='hotel.region'),
        ),
    ]
